server:
  port: 8083
spring:
  application:
    name: search-service
  elasticsearch:
    rest:
      uris:
        - http://jz-ubuntu:9200
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
